### ISSUE TITLE
Add a dropdown arrow to hide nested segments

### ISSUE THREAD

**Issue by mateuszbugaj** [Ellpeck/ObsidianSimpleTimeTracker#23]
The timer component gets long quickly when working with nested segments. We can add a dropdown arrow similar to the one used by Obsidian for bullet point lists to hide or show sub-segments.

Here's a demo of how that might look like. 
![Demo](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/38944068/07e95331-294d-471d-bd9c-8b39d434d584)

I would also like to hide an entire list of segments to make notes less cluttered, but I think that might be a separate issue since there needs to be a change in the overall layout of the component. What do you think?

**Comment by Karamellwuerfel** [comment]
Hello everyone, this issue seems to be fixed already. @Ellpeck so the issue could be closed. #53 is described in an extra issue.
