### ISSUE TITLE
Allow using Obsidian markdown in segment names

### ISSUE THREAD

**Issue by jansari-ge** [Ellpeck/ObsidianSimpleTimeTracker#25]
Hello,
Thanks a lot for your plugin in obsidian.

Could you please add more segment or more column ?
In my way of working and time tracking, I add some `#keyword` and some information or link to note `📧 mail to test [test](test.md)`

With the "segment" I cannot easly add this informations while I start the counter

This an example of manual time-tracking
date📅| heure ⏲ | timespent ⌛ | what | who🧝‍♂| subject 📔
-|:-:|:-:|-|-|-
20230726|11:43 | 00:10| `#test #test2` | - |  `📧 mail to test [test](test.md)`

This an example with your time-tracking
![image](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/140606240/a6b1d134-9794-4988-8012-7f230f33b17e)

Thanks a lot

**Comment by Karamellwuerfel** [comment]
Hi @jansari-ge,
this feature was implemented with #43.


> List of functionality:
> 1. Obsidian hashtag - #tag
> 2. Link - [link](link)
> 3. Multiple hashtag and links in Segment field
> 4. Combining text and link/tag = #tag1 text1 #tag2 [link1](link) text2

@Ellpeck you can close this issue :)
