### ISSUE TITLE
Editing time entries

### ISSUE THREAD

**Issue by LucPrestin** [Ellpeck/ObsidianSimpleTimeTracker#29]
Hi @Ellpeck 

first of all, thank you very much for this plugin. I use it almost daily and have been loving it so far.

I often find myself forgetting to start a timer when I start working. So what I usually do is to start it when I notice and edit the start date later on. However, this is somewhat inconvenient, as the times are stored as unix epoch timestamps, which means I  have to use a different tool to calculate the timestamp and paste the result over.

To improve on this, I could imagine two ways:
1. Store the times in a ISO-8601 (i.e. like `2023-10-16T14:10:10+00:00`) or similar encoding, that is human readable. This way the time could be edited through the source view.
2. Allow to edit the times through the user interface. There already is an edit button for the entry name. A click on that button could make the times editable as well and save them as unix epoch timestamps on confirmation.

From a usability standpoint, the second would probably be better, but the first one should be easier to implement.

If you want to, I could look into that. I just did not want to start anything before consulting you on this.

Cheers,
Luc

**Comment by Ellpeck** [comment]
Hi! Are you sure you're on the latest version? Both of these features have already been implemented and released.

**Comment by LucPrestin** [comment]
Oh, you're right. For some reason I wasn't shown the available updates until now. Sorry for taking up your time.
