### ISSUE TITLE
Does not render in reading view

### ISSUE THREAD

**Issue by gypsyav** [Ellpeck/ObsidianSimpleTimeTracker#31]
In reading view once a timer is started it no longer renders, it shows up as a block of code. 

Everything works as it should in live preview.

This is what I am seeing in reading view:
![ReadingView](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/26289654/5eeddd7f-7caf-4fd7-b001-c4d3ad1fe8f1)

And this is what I see in Live Preview:
![LivePreview](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/26289654/6663ddd4-b84b-42e2-b6bc-9f2de93f86dd)

**Comment by Ellpeck** [comment]
Hmm, I don't seem to be able to reproduce this on Windows Desktop? What device are you running this on, and do you have any special plugins installed that may break reading view?

**Comment by gypsyav** [comment]
I found the issue. It's not compatible with the Tables Extended plugin.

**Comment by Ellpeck** [comment]
Hi! Please reach out to the author of the Tables Extended plugin with a reference to this issue so that we can get it sorted together! I don't really see a reason why this would be happening on my end, so I'd love some insight from them :)

**Comment by gypsyav** [comment]
The Tables Extended plugin hasn't been updated in two years and a similar issue with other plugins has been reported.

**Comment by Ellpeck** [comment]
Okay! I'll close this for now, then.
