### ISSUE TITLE
A way to get time tracking data to Dataview

### ISSUE THREAD

**Issue by gokcemay** [Ellpeck/ObsidianSimpleTimeTracker#4]
If possible, getting to Dataview will be great. So that users can generate time spend on projects each week/day/month.

**Comment by OuchPotato** [comment]
I want this feature too

**Comment by limrli** [comment]
Is this function coming soon? I think it's really useful too.

**Comment by BP-ANU** [comment]
This would be incredible, any chance it's coming sometime soon?
