### ISSUE TITLE
Allow edit mode while timer is running

### ISSUE THREAD

**Issue by joaonunatings** [Ellpeck/ObsidianSimpleTimeTracker#41]
Hi, not sure why this feature was removed in 0.2.0 but I used to edit the time as it was running and now it's not possible.

**Comment by Ellpeck** [comment]
Hi! This used to cause a lot of issues and confusion for a lot of people. Can you describe why you need this feature? What specifically would you like to be able to edit? Just the name, or the active times too?

**Comment by joaonunatings** [comment]
My use case is when I forget to start the timer for a given task and I would just edit the start time immediatly after starting it.
Now I have to start, stop, edit the start time, continue again thus creating a subtimer which is not desirable.

I would like to at least edit the name and start time.

**Comment by Coeditor5852** [comment]
![Screenshot_20240308-193033_Toggl_Track](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/132636546/943ab46f-26c1-4947-a4ea-a57a872061ac)
![Screenshot_20240308-193123_Toggl_Track](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/132636546/0174a0aa-6f6d-4937-9bee-d65dc7eb9d56)

Toggl track mobile app has "Set to last time" option, which can be added to fix this issue.

**Comment by joaonunatings** [comment]
> ![Screenshot_20240308-193123_Toggl_Track|40](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/132636546/0174a0aa-6f6d-4937-9bee-d65dc7eb9d56)
> 
> ![Screenshot_20240308-193033_Toggl_Track|700](https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/132636546/943ab46f-26c1-4947-a4ea-a57a872061ac)
> 
> 
> 
> Toggl track mobile app has "Set to last stop time today" option, which can be added to fix this issue.
> 
> 

This would not work for the first task of the day, which, in my case, is the one I mostly edit the start time.

**Comment by Ellpeck** [comment]
Hi. This issue is still open and has the `enhancement` label applied to it, which was my way of communicating that this will be implemented again :)

**Comment by little-burrito** [comment]
Glad to hear it! Just came to say that I'm using it in the exact same way - forgetting to turn it on (or starting my work when I'm not with one of my devices) and then updating the start time immediately. Thank you for making a tool I use on a daily basis!

**Comment by Da-Va** [comment]
Also great to hear. I love your time tracking tool. Sorry for my last message being somewhat confrontational, there was a lot going on at work at the time.
