### ISSUE TITLE
Bug When remove Timers Unable to type

### ISSUE THREAD

**Issue by tonypuglieso** [Ellpeck/ObsidianSimpleTimeTracker#49]
Sometimes when I remove timers, the mouse is left unable to type, until I open the browser and it is fixed.

https://github.com/Ellpeck/ObsidianSimpleTimeTracker/assets/52177646/967097da-1307-4be3-ae54-a9b073729abb

**Comment by xarts19** [comment]
Same issue here, deleting the segment prevents typing until Obsidian window loses and regains focus.
