### ISSUE TITLE
Issue iterating through tracker.entries with 'subEntries'

### ISSUE THREAD

**Issue by joost8** [Ellpeck/ObsidianSimpleTimeTracker#58]
Hi @Ellpeck, absolutely love this plugin for my work time management! I am working on a DataviewJS overview of all worked hours per day per entry for my work hours administration. The script below unfortunately gives an error.

Screenshot of the error:
![image](https://github.com/user-attachments/assets/1f5db961-459e-4606-a01e-efc4147b9943)

The DataviewJS code:

```dataviewjs
let api = dv.app.plugins.plugins["simple-time-tracker"].api;

for(let page of dv.pages('#tijd-bijhouden')) {
	// load trackers in the file with the given path
	
	let trackers = await api.loadAllTrackers(page.file.path);
	
		if (trackers.length)
		dv.el("strong", "Trackers in " + page.file.name);
	
        for (let {section, tracker} of trackers) {
            let alltrackers = trackers.length;
            for( let i = 0; i <= alltrackers + 1; i++) {
                if (tracker.entries[i])
                     dv.el('p', 'doel: ' + tracker.entries[i]['name'])
                     dv.el('p', 'tijdsduur: ' + api.getDuration(tracker.entries[i]))
		}
}	
}
```

Would you have any idea what the issue could be? It works on some time trackers that have an entry without subEntries, but not on some others which do have subEntries.

**Comment by joost8** [comment]
Never mind, I just 'fixed' this (the issue was with my DataviewJS-code).

I needed to have all my output in the same dv.el(), there was probably some problem with the iteration in the code before. One *final* thing I would like is to have the output sorted by date, if I have that, I will put it here in case anyone wants the same thing.

```dataviewjs
let api = dv.app.plugins.plugins["simple-time-tracker"].api;

for(let page of dv.pages('#tijd-bijhouden')) {
	// load trackers in the file with the given path
	
	let trackers = await api.loadAllTrackers(page.file.path);
	
		if (trackers.length)
		dv.el("strong", "Trackers in " + page.file.name);
	
        for (let {section, tracker} of trackers) {
            let alltrackers = trackers.length;
            for( let i = 0; i <= alltrackers + 1; i++) {
                if (tracker.entries[i])
                     dv.el('p', 'doel: ' + tracker.entries[i]['name'] + '<br>' + 'tijdsduur: ' + api.formatDuration(api.getDuration(tracker.entries[i])))
		}
}	
}
```

**Comment by Ellpeck** [comment]
Hi! The only issue I'm immediately noticing with your code is that you're iterating way over the total amount of trackers for seemingly no reason, unless I'm misunderstanding something? 

You iterate from 0 to `alltrackers.length + 1` inclusive, which is two more than there are actually entries. The correct way to structure the for loop would be something like
```js
for( let i = 0; i < alltrackers; i++) {
```

Note the removal of the `=` in the `<` check, too :)

This way, you also don't have to check whether `tracker.entries[i]` is truthy.

**Comment by Ellpeck** [comment]
Also, you can sort the trackers roughly by date using code something like the following:
```js
let sorted = trackers.toSorted((a, b) => moment(a.entries[0].startTime).diff(moment(b.entries[0].startTime)));
```
(Or swapping `a` and `b`'s usage to sort the other way)

This is untested, so there might be a few small things to change, though!

**Comment by joost8** [comment]
Thanks! I have no prior experience with JavaScript, so the script is very cobbled together. These comments are great, I will incorporate them when I can. The end goal would be to have some sort of dynamic table, to give an easy overview of dates and hours spent on different tasks. Maybe dv.table() will help, but I don't know if it allows for looping through arrays or dictionaries.

**Comment by Ellpeck** [comment]
I think with `dv.table()`, you can also just give it an array or dictionary or some sort of data structure directly, rather than a dataview query. That would allow you to be able to collect the data together through your script, and then make a table out of it :)
