### ISSUE TITLE
List of segments

### ISSUE THREAD

**Issue by dionvansevenant** [Ellpeck/ObsidianSimpleTimeTracker#7]
Future suggestion: provide a list of segments to choose from when starting a timer.

Perhaps based on existing segments in the current timer block, with an option to type in a new one.

Or, based on a pre-defined list.

When switching between the same named segments during the work day, having to type them in can lead to errors.

Thanks!

**Comment by Ellpeck** [comment]
So, just to clarify, when starting a new segment you want to have the ability to use a pre-defined *segment name* for a new segment? That sounds like a good idea.

Any reason you're not just using sub-segments by continuing an existing segment, though?

**Comment by dionvansevenant** [comment]
Fair question. I actually missed that functionality as the additional
buttons for sub-segments do not appear when a timer is running.

I will actually try using sub segments and see how that goes.

But, yes, my initial query was for a pre-defined *segment name*.

Thanks for the quick reply!

Dion

**Comment by Karamellwuerfel** [comment]
Hi @dionvansevenant, is your suggestion / feature request still relevant or could the problem be solved by using the sub-segments?

Thank you very much!

**Comment by Ellpeck** [comment]
Okay, I'll close this then! :)
